### PR TITLE
Example of using Docker binary actions and serverless framework.

### PR DESCRIPTION
**Pull request by jthomas**
❗️DO NOT MERGE❗️

I've re-worked one of the actions (`github-user-aggregator`) to show a different approach to build and deployment. This PR demonstrates the changes required for that action. 

## what?

- Use the standard `dockerskeleton` image with the Go binary in a zip, rather than building and deploying a custom image per action.
- Use serverless framework to manage build and deployment steps. 

## how? 

Assuming you have node and npm installed...

### install serverless framework and openwhisk plugin

- `npm install --global serverless serverless-openwhisk`

### install project plugins

- `npm install` in the project directory.

### create credentials file

create a new `credentials.yml` file with the following contents.

```
GithubAccessToken: AUTH_KEY
GithubOrgs:
  - ORG_NAMES
```
### deploy

- `serverless deploy`

Building Go binaries for OpenWhisk is handled automatically using a custom build script and event hook.

### invoke

- `serverless invoke -f github-user-aggregator`

## why? 

Using the existing `dockerskeleton` image, with the Go binaries provided in a zip file, means you don't have to build and expose custom Docker images on Docker Hub per action. Startup time should be much faster for cold invocations as the images exist in the platform.

The Serverless Framework handles the manual steps involved in packaging, deploying and configuring OpenWhisk applications. No more manual `wsk` commands for deployments. I've also hook up an auto-build script to the deployment. When the `serverless deploy` command is ran, the `npm run build` command is triggered prior to deployment. This runs the Go build to generate the correct platform binary. 

**I would definitely recommend using the `dockerskeleton` image over building custom images per action. Using the framework is more of a personal choice, you could just adapt the existing Python script to handle the new build and deploy process instead.**

## good/bad?

If you want to incorporate some or all of these changes, let me know and I'll update the rest of the project to match the example above.

### CODE REVIEW

**Comment by tleyden** [comment]
That's the direction I started, but I ran into https://github.com/apache/incubator-openwhisk/issues/2465, and then pivoted back to a pure Go/Docker approach to avoid that problem.  The downside is that it makes the build process more clunky and the action startup time slightly slower.  

Native Golang support in OpenWhisk would make all this moot though.  Are there any huge blockers there or is it just something on the todo list?  Should I file an issue in the OpenWhisk repo?

**Comment by jthomas** [comment]
Here's the solution for the issue referenced above. OpenWhisk allows you to provide a Docker image and an archive file to deploy for an action. I'm modified the `actionproxy.py` file to pass input through `stdin` rather than an environment variable. This has been built and pushed to docker hub at `jamesthomas/custom_skeleton`. 

https://gist.github.ibm.com/thomas6/99558d3c64bb8f571fe55c3cdd1b3817#file-actionproxy-py-L128-L141

Now we can use the stdin-based handlers with this base image, without having to build a custom image per action. Here's an example Go application just returns the input parameters.

```go
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
)

func main() {
	bytes, err := ioutil.ReadAll(os.Stdin)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s", bytes)
}
```

This will now work as follows....

```
$ env GOOS=linux GOARCH=amd64 go build -o exec main.go
$ zip action.zip exec
$ wsk action create custom_skeleton --docker jamesthomas/custom_skeleton action.zip
$ wsk action invoke custom_skeleton --blocking --param hello world
```

I'll have a go at updating the project tomorrow to use this new approach.

**Comment by jthomas** [comment]
I've pushed more commits that now changed all the `main.go` files over to use the new stdin handler. I've also updated the Python script to drop the Docker build step and use the create `wsk action create` command. 

**There's an issue with the Serverless Framework which I'll need to resolve before the works.**

**Comment by tleyden** [comment]
Looks great!  The only thing that worries me is that jamesthomas/custom_skeleton is fairly opaque.  Is it possible to make that an automated build that pulls the Dockerfile fom a public github repo?

**Pull request merged**
